export * from './CategoriaPage'
export * from './MarcaPage';
export * from './EquipoInformaticoPage';
export * from './IncidenciaPage';
export * from './ListEquipos';
export * from './ListDocentes';
export * from './EquipoPrestamo';
export * from './ListEquipoPrestamo';
export * from './ListPrestamos';
export * from './ListIncidencia';
export * from './ListCategorias';
export * from './ListMarcas';
export * from './PrestamoPage';
export * from './DocentePage';